import { sql } from "drizzle-orm";

import { db } from "../src/server/db";
import { district, region } from "../src/server/db/schema";

const ghanaRegions = [
	{
		code: "AR",
		name: "Ashanti Region",
		districts: [
			{ code: "AAN", name: "Asante Akim North" },
			{ code: "AAC", name: "Asante Akim Central" },
			{ code: "AAS", name: "Asante Akim South" },
			{ code: "AFK", name: "Afigya Kwabre North" },
			{ code: "AFS", name: "Afigya Kwabre South" },
			{ code: "ATN", name: "Atwima Nwabiagya North" },
			{ code: "ATS", name: "Atwima Nwabiagya South" },
			{ code: "ATM", name: "Atwima Mponua" },
			{ code: "BOS", name: "Bosomtwe" },
			{ code: "EJI", name: "Ejisu" },
			{ code: "EJS", name: "Ejura Sekyedumase" },
			{ code: "KUM", name: "Kumasi Metropolitan" },
			{ code: "KWA", name: "Kwabre East" },
			{ code: "MAM", name: "Mampong Municipal" },
			{ code: "OBE", name: "Obuasi East" },
			{ code: "OBW", name: "Obuasi West" },
			{ code: "OFN", name: "Offinso North" },
			{ code: "OFS", name: "Offinso South" },
			{ code: "SEK", name: "Sekyere Afram Plains" },
			{ code: "SEC", name: "Sekyere Central" },
			{ code: "SEE", name: "Sekyere East" },
			{ code: "SKW", name: "Sekyere Kumawu" },
			{ code: "SES", name: "Sekyere South" },
			{ code: "SUAM", name: "Suame" },
			{ code: "ASO", name: "Asokwa" },
			{ code: "MAN", name: "Manhyia" },
			{ code: "SUB", name: "Subin" },
			{ code: "NHU", name: "Nhyiaeso" },
		],
	},
	{
		code: "BA",
		name: "Bono Region",
		districts: [
			{ code: "BAN", name: "Banda" },
			{ code: "BER", name: "Berekum East" },
			{ code: "BEW", name: "Berekum West" },
			{ code: "DOR", name: "Dormaa Central" },
			{ code: "DOE", name: "Dormaa East" },
			{ code: "DOW", name: "Dormaa West" },
			{ code: "JAN", name: "Jaman North" },
			{ code: "JAS", name: "Jaman South" },
			{ code: "SUN", name: "Sunyani Municipal" },
			{ code: "SUW", name: "Sunyani West" },
			{ code: "TAIN", name: "Tain" },
			{ code: "WEN", name: "Wenchi" },
		],
	},
	{
		code: "BE",
		name: "Bono East Region",
		districts: [
			{ code: "ATE", name: "Atebubu Amantin" },
			{ code: "KIN", name: "Kintampo North" },
			{ code: "KIS", name: "Kintampo South" },
			{ code: "NKN", name: "Nkoranza North" },
			{ code: "NKS", name: "Nkoranza South" },
			{ code: "PRU", name: "Pru East" },
			{ code: "PRW", name: "Pru West" },
			{ code: "SEN", name: "Sene East" },
			{ code: "SEW", name: "Sene West" },
			{ code: "TEC", name: "Techiman South" },
			{ code: "TEH", name: "Techiman North" },
		],
	},
	{
		code: "AH",
		name: "Ahafo Region",
		districts: [
			{ code: "ASU", name: "Asunafo North" },
			{ code: "ASS", name: "Asunafo South" },
			{ code: "ASF", name: "Asutifi North" },
			{ code: "AST", name: "Asutifi South" },
			{ code: "TAN", name: "Tano North" },
			{ code: "TAS", name: "Tano South" },
		],
	},
	{
		code: "CR",
		name: "Central Region",
		districts: [
			{ code: "ABK", name: "Abura Asebu Kwamankese" },
			{ code: "AGE", name: "Agona East" },
			{ code: "AGW", name: "Agona West" },
			{ code: "AJU", name: "Ajumako Enyan Essiam" },
			{ code: "ASF", name: "Assin Foso" },
			{ code: "ASN", name: "Assin North" },
			{ code: "ASS", name: "Assin South" },
			{ code: "AWU", name: "Awutu Senya East" },
			{ code: "AWS", name: "Awutu Senya West" },
			{ code: "CAP", name: "Cape Coast" },
			{ code: "EFF", name: "Effutu" },
			{ code: "EKU", name: "Ekumfi" },
			{ code: "GOM", name: "Gomoa East" },
			{ code: "GOW", name: "Gomoa West" },
			{ code: "KOM", name: "Komenda-Edina-Eguafo-Abirem" },
			{ code: "MFA", name: "Mfantsiman" },
			{ code: "TWE", name: "Twifo Ati Morkwa" },
			{ code: "HEM", name: "Hemang Lower Denkyira" },
			{ code: "UDE", name: "Upper Denkyira East" },
			{ code: "UDW", name: "Upper Denkyira West" },
			{ code: "WIN", name: "Winneba Municipal" },
			{ code: "AOB", name: "Asikuma Odoben Brakwa" },
		],
	},
	{
		code: "ER",
		name: "Eastern Region",
		districts: [
			{ code: "ABN", name: "Abuakwa North" },
			{ code: "ABS", name: "Abuakwa South" },
			{ code: "ASU", name: "Asuogyaman" },
			{ code: "ATE", name: "Atiwa East" },
			{ code: "ATW", name: "Atiwa West" },
			{ code: "AYE", name: "Ayensuano" },
			{ code: "BIC", name: "Birim Central" },
			{ code: "BIN", name: "Birim North" },
			{ code: "BIS", name: "Birim South" },
			{ code: "DEN", name: "Denkyembour" },
			{ code: "FAN", name: "Fanteakwa North" },
			{ code: "FAS", name: "Fanteakwa South" },
			{ code: "KWA", name: "Kwaebibirem" },
			{ code: "LMK", name: "Lower Manya Krobo" },
			{ code: "NJS", name: "New Juaben South" },
			{ code: "NJN", name: "New Juaben North" },
			{ code: "NSA", name: "Nsawam Adoagyiri" },
			{ code: "SUH", name: "Suhum" },
			{ code: "WAK", name: "West Akim" },
			{ code: "UWK", name: "Upper West Akim" },
			{ code: "YIL", name: "Yilo Krobo" },
		],
	},
	{
		code: "GA",
		name: "Greater Accra Region",
		districts: [
			{ code: "GAS", name: "Ga South" },
			{ code: "WEI", name: "Weija Gbawe" },
			{ code: "GAC", name: "Ga Central" },
			{ code: "GAN", name: "Ga North" },
			{ code: "GAW", name: "Ga West" },
			{ code: "GAE", name: "Ga East" },
			{ code: "LNM", name: "La Nkwantanang Madina" },
			{ code: "ABS", name: "Ablekuma South Sub-Metro" },
			{ code: "AYE", name: "Ayawaso East" },
			{ code: "AYN", name: "Ayawaso North" },
			{ code: "AYC", name: "Ayawaso Central" },
			{ code: "AYW", name: "Ayawaso West" },
			{ code: "OKS", name: "OkaiKwei South Metro" },
			{ code: "ASH", name: "Ashiedu Keteke Sub-Metro" },
			{ code: "OKN", name: "OkaiKwei North" },
			{ code: "ABN", name: "Ablekuma North" },
			{ code: "ABC", name: "Ablekuma Central" },
			{ code: "ABW", name: "Ablekuma West" },
			{ code: "KOR", name: "Korley Klottey" },
			{ code: "LAD", name: "La Dadekotopon" },
			{ code: "LED", name: "Ledzokuku" },
			{ code: "KRO", name: "Krowor" },
			{ code: "TEM", name: "Tema Metro" },
			{ code: "TEW", name: "Tema West" },
			{ code: "KPO", name: "Kpong Katamanso" },
			{ code: "ASHM", name: "Ashaiman" },
			{ code: "ADE", name: "Adentan" },
			{ code: "SHO", name: "Shai Osudoku" },
			{ code: "NIN", name: "Ningo Prampram" },
			{ code: "ADW", name: "Ada West" },
			{ code: "ADEE", name: "Ada East" },
		],
	},
	{
		code: "NR",
		name: "Northern Region",
		districts: [
			{ code: "BOLE", name: "Bole" },
			{ code: "BUY", name: "Bunkpurugu Yunyoo" },
			{ code: "CGO", name: "Central Gonja" },
			{ code: "CHP", name: "Chereponi" },
			{ code: "EGO", name: "East Gonja" },
			{ code: "GUS", name: "Gushiegu" },
			{ code: "KAR", name: "Karaga" },
			{ code: "KPA", name: "Kpandai" },
			{ code: "KUM", name: "Kumbungu" },
			{ code: "MIO", name: "Mion" },
			{ code: "NNM", name: "Nanumba North Municipal" },
			{ code: "NNS", name: "Nanumba South" },
			{ code: "SAB", name: "Saboba" },
			{ code: "SAN", name: "Sagnarigu" },
			{ code: "SAV", name: "Savelugu" },
			{ code: "TAM", name: "Tamale Metro" },
			{ code: "TAS", name: "Tatale Sanguli" },
			{ code: "TOL", name: "Tolon" },
			{ code: "WGO", name: "West Gonja" },
			{ code: "YEN", name: "Yendi" },
			{ code: "ZAB", name: "Zabzugu" },
		],
	},
	{
		code: "OR",
		name: "Oti Region",
		districts: [
			{ code: "BIA", name: "Biakoye" },
			{ code: "JAS", name: "Jasikan" },
			{ code: "KAJ", name: "Kadjebi" },
			{ code: "KEE", name: "Krachi East" },
			{ code: "KEW", name: "Krachi West" },
			{ code: "KEN", name: "Krachi Nchumuru" },
			{ code: "NKW", name: "Nkwanta South" },
			{ code: "NKN", name: "Nkwanta North" },
			{ code: "OTI", name: "Oti" },
			{ code: "SAL", name: "Sall Municipal" },
		],
	},
	{
		code: "UE",
		name: "Upper East Region",
		districts: [
			{ code: "BAW", name: "Bawku Municipal" },
			{ code: "BAWW", name: "Bawku West" },
			{ code: "BIN", name: "Binduri" },
			{ code: "BOL", name: "Bolgatanga Municipal" },
			{ code: "BON", name: "Bongo" },
			{ code: "BUN", name: "Builsa North" },
			{ code: "BUS", name: "Builsa South" },
			{ code: "GAR", name: "Garu" },
			{ code: "TEM", name: "Tempane" },
			{ code: "KNE", name: "Kassena Nankana East" },
			{ code: "KNW", name: "Kassena Nankana West" },
			{ code: "NAB", name: "Nabdam" },
			{ code: "PUS", name: "Pusiga" },
			{ code: "TAL", name: "Talensi" },
		],
	},
	{
		code: "UW",
		name: "Upper West Region",
		districts: [
			{ code: "WAM", name: "Wa Municipal" },
			{ code: "WAW", name: "Wa West" },
			{ code: "WAE", name: "Wa East" },
			{ code: "LAW", name: "Lawra" },
			{ code: "JIR", name: "Jirapa" },
			{ code: "SIE", name: "Sissala East" },
			{ code: "SIW", name: "Sissala West" },
			{ code: "NAK", name: "Nadowli Kaleo" },
			{ code: "NAN", name: "Nandom" },
			{ code: "LAM", name: "Lambussie" },
			{ code: "DAF", name: "Daffiama Bussie Issa" },
		],
	},
	{
		code: "VR",
		name: "Volta Region",
		districts: [
			{ code: "ADA", name: "Adaklu" },
			{ code: "AFS", name: "Afadzato South" },
			{ code: "AGO", name: "Agotime Ziope" },
			{ code: "AKN", name: "Akatsi North" },
			{ code: "AKS", name: "Akatsi South" },
			{ code: "BIA", name: "Biakoye" },
			{ code: "CTO", name: "Central Tongu" },
			{ code: "HOM", name: "Ho Municipal" },
			{ code: "HOW", name: "Ho West" },
			{ code: "HOO", name: "Hohoe Municipal" },
			{ code: "JAS", name: "Jasikan" },
			{ code: "KAJ", name: "Kadjebi" },
			{ code: "KET", name: "Keta Municipal" },
			{ code: "KTN", name: "Ketu North" },
			{ code: "KTS", name: "Ketu South" },
			{ code: "KEE", name: "Krachi East" },
			{ code: "KEW", name: "Krachi West" },
			{ code: "KEN", name: "Krachi Nchumuru" },
			{ code: "NKW", name: "Nkwanta South" },
			{ code: "NKN", name: "Nkwanta North" },
			{ code: "NDY", name: "North Dayi" },
			{ code: "NTO", name: "North Tongu" },
			{ code: "SDY", name: "South Dayi" },
			{ code: "STO", name: "South Tongu" },
		],
	},
	{
		code: "WN",
		name: "Western North Region",
		districts: [
			{ code: "AOW", name: "Aowin" },
			{ code: "SUAM", name: "Suaman" },
			{ code: "BIB", name: "Bibiani Anhwiaso Bekwai" },
			{ code: "SEW", name: "Sefwi Wiawso" },
			{ code: "SEK", name: "Sefwi Akontombra" },
			{ code: "JUA", name: "Juaboso" },
			{ code: "BOD", name: "Bodi" },
			{ code: "BIAW", name: "Bia West" },
			{ code: "BIAE", name: "Bia East" },
		],
	},
	{
		code: "WR",
		name: "Western Region",
		districts: [
			{ code: "AHW", name: "Ahanta West" },
			{ code: "ELL", name: "Ellembelle" },
			{ code: "JOM", name: "Jomoro" },
			{ code: "MPO", name: "Mpohor" },
			{ code: "NZE", name: "Nzema East" },
			{ code: "PRE", name: "Prestea Huni Valley" },
			{ code: "SHA", name: "Shama" },
			{ code: "TAK", name: "Takoradi" },
			{ code: "SEK", name: "Sekondi" },
			{ code: "ESS", name: "Essikado Ketan" },
			{ code: "EFK", name: "Effia Kwesimintsim" },
			{ code: "WAS", name: "Wassa East" },
			{ code: "WAC", name: "Wassa Amenfi Central" },
			{ code: "WAE", name: "Wassa Amenfi East" },
			{ code: "WAW", name: "Wassa Amenfi West" },
			{ code: "WAM", name: "Wassaman" },
		],
	},
	{
		code: "NE",
		name: "North East Region",
		districts: [
			{ code: "WMA", name: "West Mamprusi" },
			{ code: "EMA", name: "East Mamprusi" },
			{ code: "BUY", name: "Bunkpurugu Yunyoo" },
			{ code: "YUN", name: "Yunyoo Nasuan" },
			{ code: "MAM", name: "Mamprugu Moagduri" },
			{ code: "CHE", name: "Chereponi" },
			{ code: "BIN", name: "Binduri" },
			{ code: "GAM", name: "Gamaga" },
			{ code: "NAL", name: "Nalerigu" },
		],
	},
	{
		code: "SR",
		name: "Savannah Region",
		districts: [
			{ code: "BOLE", name: "Bole" },
			{ code: "SAW", name: "Sawla Tuna Kalba" },
			{ code: "WGO", name: "West Gonja" },
			{ code: "NGO", name: "North Gonja" },
			{ code: "CGO", name: "Central Gonja" },
			{ code: "EGO", name: "East Gonja" },
			{ code: "NEG", name: "North East Gonja" },
		],
	},
];

const slugify = (value: string) =>
	value
		.normalize("NFKD")
		.replace(/[\u0300-\u036f]/g, "")
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^[-]+|[-]+$/g, "");

async function main() {
	const regionValues = ghanaRegions.map((regionEntry) => ({
		code: regionEntry.code,
		name: regionEntry.name,
	}));

	const districtValues = ghanaRegions.flatMap((regionEntry) =>
		regionEntry.districts.map((districtEntry) => ({
			id: `${regionEntry.code.toLowerCase()}-${slugify(districtEntry.name)}`,
			name: districtEntry.name,
			code: districtEntry.code,
			regionCode: regionEntry.code,
		})),
	);

	// neon-http driver does not support transactions, so perform sequential upserts.
	await db
		.insert(region)
		.values(regionValues)
		.onConflictDoUpdate({
			target: region.code,
			set: { name: sql`excluded.name` },
		});

	await db
		.insert(district)
		.values(districtValues)
		.onConflictDoUpdate({
			target: district.id,
			set: {
				name: sql`excluded.name`,
				code: sql`excluded.code`,
				regionCode: sql`excluded.region_code`,
			},
		});

	process.stdout.write(
		`Seeded ${regionValues.length} regions and ${districtValues.length} districts.\n`,
	);
}

main().catch((error) => {
	process.stderr.write(
		`Failed to seed districts: ${error instanceof Error ? error.message : String(error)}\n`,
	);
	process.exit(1);
});
